export const keyMap = new Map<string, string>([
  ['REMITO', 'remittance'],
  ['Fecha Envio al Proveedor', 'orderedDate'],
  ['Empresa Proveedora', 'providerFactory'],
  ['Solicitud', 'orderNumber'],
  ['Sucursal', 'office'],
  ['Busqueda', 'searchBy'],
  ['Tramite', 'orderType'],
  ['Denominacion', 'firstName'],
  ['Nro Documento', 'dni'],
  ['Tipo de Persona', 'ownerType'],
  ['Tipo de Documento', 'dniType'],
  ['Domicilio Calle', 'adress'],
  ['Numero', 'streetNumber'],
  ['Piso', 'adressFloor'],
  ['Departamento', 'apartmentNumber'],
  ['Localidad', 'city'],
  ['Dto/Distrito/Partido', 'department'],
  ['Provincia', 'state'],
  ['Matricula N°', 'enrollmentNumber'],
  ['Tomo', 'volumeNumber'],
  ['Folio', 'folioNumber'],
  ['Dominio', 'domain'],
  ['N° entrada a Registro', 'registryEnterNumber'],
  ['Año de Inscripción', 'yearNumber'],
  ['Dpto/Distrito/Partido', 'district'],
  ['Observaciones', 'observations'],
]);
